# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e1b010af8d74dc2e92d18b90fa93b3e865adb462514d64a659083aa1fabdcb4350ebfb35a6d92147b18f356588f4accccaa8129045943772f0520ec0a8e7231e

test:
  secret_key_base: a5b57a780348ccb07a3520e62965c663f8ed06c9351da054dce0a094330969c0f9fa6434ed28ceb67a1e7d0d6323fb9910b2ae07bfb1386eb8df26f38bdf7ffd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
